application: fit-05
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /test\.html
  static_files: static/test.html
  upload: static/test\.html
  
- url: .*
  script: myproject.wsgi.application

libraries:
- name: django
  version: 1.5
